id: P350D72D4
initial_creation_type: ocr
source_metadata:
  volumes:
    49257bb7d9914fbca3e9da63f4eae2af:
      base_file: v012.txt
      image_group_id: I1PD95857
      title: རྡོ་རྗེ་ཕག་མོའི་སྒྲུབ་པའི་ཐབས།
      total_pages: 1544
      volume_number: 12
